FROM phpdoc/phpdoc:3.4 as doc_builder

COPY . /source

WORKDIR /source

RUN mkdir /target && \
    phpdoc run \
        -d 'core/classes' \
        -d 'modules/Core/classes' \
        -d 'modules/Discord Integration/classes' \
        -d 'modules/Cookie Consent/classes' \
        -d 'modules/Forum/classes' \
        -d 'modules/Members/classes' \
        -i vendor \
        -t /target

FROM nginxinc/nginx-unprivileged:stable

COPY --from=doc_builder /target /usr/share/nginx/html
