name: Feature request
description: Suggest a feature we can add to NamelessMC
labels: ["enhancement"]
body:
- type: textarea      
  attributes:
    label: Describe the feature
    description: Please describe the feature in as much detail as possible.
  validations:
    required: true
