name: CI

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer update --no-interaction --no-suggest --no-progress

      - name: Execute PHPStan
        run: vendor/bin/phpstan --configuration=dev/phpstan.neon

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          cli: -q --standard=dev/phpcs.xml

  unused-language-term-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unused language term check
        run: bash dev/scripts/find_unused_language_terms.sh
